version: '3.8'  

services:
  pneumonia_classifier_api:  
    image: nicoleolv/pneumonia_classifier_api  
    build:
      context: .  
      dockerfile: Dockerfile  
    ports:
      - "5000:5000" 
    volumes:
      - ./models:/models  # mount models directory 
    restart: unless-stopped  
    entrypoint: ["python", "api.py"]
